[package]
name = "duplicate-finder"
version = "0.1.0"
authors = ["Stuart Dootson <stuart.dootson@gmail.com>"]

[dependencies]
custom_derive = "^0.1"
enum_derive = "^0.1"
ignore = "^0.2"
multimap = "^0.4"
rayon = "^0.8"
structopt = "^0.1"
structopt-derive = "^0.1"
