[package]
name = "duplicate-finder"
version = "0.1.0"
authors = ["Stuart Dootson <stuart.dootson@gmail.com>"]
edition = "2018"

[dependencies]
ignore = "^0.4"
multimap = "^0.8"
rayon = "^1.3"
structopt = "^0.3"
structopt-derive = "^0.4"
num_cpus = "^1.13"